Jeu : main.c fonctionCommune.o grilleDifficile.o grilleFacile.o userPlayDiff.o userPlayFac.o
	gcc -g -Wall -o Jeu main.c fonctionCommune.o grilleDifficile.o grilleFacile.o userPlayDiff.o userPlayFac.o

fonctionCommune.o : fonctionCommune.c header.h
	gcc -g -Wall -c fonctionCommune.c

grilleDifficile.o : grilleDifficile.c header.h
	gcc -g -Wall -c grilleDifficile.c

grilleFacile.o : grilleFacile.c header.h
	gcc -g -Wall -c grilleFacile.c

userPlayDiff.o : userPlayDiff.c header.h
	gcc -g -Wall -c userPlayDiff.c

userPlayFac.o : userPlayFac.c header.h
	gcc -g -Wall -c userPlayFac.c
